version: "3.3"

networks:

  servicebus:
    external: true

  proxy:
    external: true

services:

  rmq1:
    image: rabbitmq:3.6-management
    hostname: rmq1
    environment:
      ERLANG_COOKIE: ${ERLANG_COOKIE}
      TCP_PORTS: "5672,15672"
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RMQ_PASSWORD}
    volumes:
      - rmq1:/var/lib/rabbitmq
    networks:
      - proxy
      - servicebus
    deploy:
      resources:
        reservations:
          memory: 4G
        limits:
          memory: 4G
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 30s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=15672
        - com.df.serviceDomain=${RMQ1_DOMAIN}
        - com.df.letsencrypt.host=${RMQ1_DOMAIN}
        - com.df.letsencrypt.email=${LETS_ENCRYPT_EMAIL}

  redis:
    image: redis:4.0-alpine
    networks:
      - servicebus
    volumes:
      - redis:/data
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 128M

volumes:

  rmq1:
    driver: cloudstor:aws
    external: false

  redis:
    driver: cloudstor:aws
    external: false
